38 build error message component emimint
chingu-voyages/v46-tier2-team-20 pull request #55
Opened 2023-11-01 19:55 UTC by Emimint

Create a component that we can later customize, that display error messages. Let me know if it needs to be fixed.

2023-11-10 23:11 UTC, Emimint commented
What changes did you make?

    In the end, I created two separate components: the StatusMessage component is displayed where there is a successfull fetch (status code 200) but with no match; the ErrorMessage component is displayed in any other situations.

Why did you make these changes?

    We want to give the users a visual indicator of response they get from their search.

Visual changes

   Case where the fetch fails (here I removed the API key to test it):

![image](https://github.com/chingu-voyages/v46-tier2-team-20/assets/90863470/1a175d97-aa33-4306-a94d-4fb274c7ed99)

Case where the fetch is successfull but with no recipe to show : 

![image](https://github.com/chingu-voyages/v46-tier2-team-20/assets/90863470/77e436b5-4f1c-4e86-8fec-f16d8d530495)

2023-11-17 19:38 UTC, allison-truhlar approved these changes

2023-11-17 19:39 UTC, allison-truhlar requested changes
Test

2023-11-17 19:50 UTC, allison-truhlar approved these changes

2023-11-17 19:56 UTC, merged